name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run backend tests
      run: npm test -- --passWithNoTests

    - name: Install dependencies
      run: npm install

    - name: Run frontend tests
      run: npm run test:frontend
      continue-on-error: true  # Optional: don't fail the build if frontend tests are flaky
